name: Java CI/CD Pipeline

   on:
     push:
       branches:
         - main
     pull_request:

   jobs:
     test:
       name: Build and Test Java Project
       runs-on: ${{ matrix.os }}
       strategy:
         matrix:
           os: [ubuntu-latest, windows-latest, macos-latest]
           java-version: ['17']

       steps:
         - name: Checkout Repo
           uses: actions/checkout@v3

         - name: Setup Java
           uses: actions/setup-java@v3
           with:
             distribution: 'temurin'
             java-version: ${{ matrix.java-version }}

         - name: Install Dependencies (Maven)
           run: mvn install --batch-mode

         - name: Compile Project
           run: mvn compile

         - name: Run Tests
           run: mvn test
